# Generated by Django 5.1.4 on 2026-05-11 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='specialisation',
            new_name='specialization',
        ),
    ]
