# Generated by Django 6.0 on 2026-05-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_cars_id_alter_mechanic_id_alter_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='task',
            name='promised_completion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
