# Generated by Django 6.0 on 2026-05-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_mechanic_is_manually_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Work estimate in hours; used to calculate promised completion when you save.', max_digits=4, null=True),
        ),
    ]
