# Generated by Django 6.0 on 2026-05-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_shop_manager_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Shop Manager')


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_task_estimated_hours_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional login for this mechanic (restricted to assigned tasks only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(ensure_shop_manager_group, migrations.RunPython.noop),
    ]
